-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.employees
(
    emp_id bigserial,
    first_name character varying(50),
    surname character varying(50),
    gender character(1),
    address character varying(100),
    email character varying(50),
    depart_id bigserial,
    role_id bigserial,
    salary_id bigserial,
    overtime_id bigserial,
    PRIMARY KEY (emp_id)
);

CREATE TABLE IF NOT EXISTS public.department
(
    depart_id bigserial,
    depart_name character varying(50),
    depart_city character varying(50),
    PRIMARY KEY (depart_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id bigserial,
    role character varying(50),
    PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.salaries
(
    salary_id bigserial,
    salary_pa numeric(10, 2),
    PRIMARY KEY (salary_id)
);

CREATE TABLE IF NOT EXISTS public.overtime_hours
(
    overtime_id bigserial,
    overtime_hours numeric(5, 2),
    PRIMARY KEY (overtime_id)
);

ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (depart_id)
    REFERENCES public.department (depart_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (salary_id)
    REFERENCES public.salaries (salary_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (overtime_id)
    REFERENCES public.overtime_hours (overtime_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;


-- ============================== INSERT STATEMENTS ==============================

INSERT INTO department (depart_name, depart_city)
VALUES 
('HR', 'Klerksdorp'),
('Finance', 'Potchefstroom'),
('IT', 'Orkney');
SELECT * FROM department


INSERT INTO roles (role)
VALUES 
('HR Manager'),
('Accountant'),
('Software Developer');
SELECT * FROM roles


INSERT INTO salaries (salary_pa)
VALUES 
('144000'),
('216000'),
('240000');
SELECT * FROM salaries


INSERT INTO overtime_hours (overtime_hours)
VALUES 
('30.30'),
('10'),
('100');
SELECT * FROM overtime_hours


INSERT INTO employees (first_name, surname, gender, address, email, depart_id, role_id, salary_id, overtime_id)
VALUES 
('John', 'Smith', 'F', '7 Bellevue Drive Klerksdorp North West 2571', 'john@email.com', 1, 1, 1, 1),
('Nadine', 'Rivers', 'F', '29 Oceans Way Potchefstroom North West 2520', 'nadine@email.com', 2, 2, 2, 2),
('Tracy', 'September', 'F', '77 Washington Road Orkney North West 2620', 'bhabha@email.com', 3, 3, 3, 3);
SELECT * FROM employees

UPDATE overtime_hours
SET overtime_hours = 100
WHERE overtime_id = 3


-- ============================================== LEFT JOIN =================================================================

SELECT emp.emp_id, 
emp.first_name, 
emp.surname, 
dept.depart_name, 
roles.role AS job_title,
sal.salary_pa,
ot.overtime_hours
FROM employees AS emp 
LEFT JOIN department AS dept
ON emp.depart_id = dept.depart_id 
LEFT JOIN roles 
ON emp.role_id = roles.role_id
LEFT JOIN salaries AS sal
ON emp.salary_id = sal.salary_id
LEFT JOIN overtime_hours AS ot
ON emp.overtime_id = ot.overtime_id
ORDER BY emp_id 


-- ============================================== TESTING CONSTRAINTS =================================================================

INSERT INTO employees (first_name, surname, gender, address, email, depart_id, role_id, salary_id, overtime_id)
VALUES 
('Dylan', 'Dundee', 'M', '23 Doringham Dunes', 'dylan@email.com', 4, 1, 1, 1);
-- ERROR:  insert or update on table "employees" violates foreign key constraint "employees_depart_id_fkey"
-- Detail: Key (depart_id)=(4) is not present in table "department".


INSERT INTO employees (first_name, surname, gender, address, email, depart_id, role_id, salary_id, overtime_id)
VALUES 
('Ronald', 'Radebe', 'M', '24 Rowling Road', 'ronald@email.com', 1, 5, 1, 1);
-- ERROR:  insert or update on table "employees" violates foreign key constraint "employees_role_id_fkey"
-- Detail: Key (role_id)=(5) is not present in table "roles".


INSERT INTO employees (first_name, surname, gender, address, email, depart_id, role_id, salary_id, overtime_id)
VALUES 
('Sally', 'Samuels', 'F', '25 Sterling Street', 'sally@email.com', 1, 1, 6, 1);
-- ERROR:  insert or update on table "employees" violates foreign key constraint "employees_salary_id_fkey"
-- Detail: Key (salary_id)=(6) is not present in table "salaries".


INSERT INTO employees (first_name, surname, gender, address, email, depart_id, role_id, salary_id, overtime_id)
VALUES 
('Omarion', 'October', 'M', '26 Oakly Okes', 'omarion@email.com', 1, 1, 1, 7);
-- ERROR:  insert or update on table "employees" violates foreign key constraint "employees_overtime_id_fkey"
-- Detail: Key (overtime_id)=(7) is not present in table "overtime_hours".







