-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.my_contacts
(
    contact_id bigserial,
    last_name character varying(30),
    first_name character varying(30) NOT NULL,
    phone character(10),
    email character varying(40),
    gender character(1) NOT NULL,
    birthday date NOT NULL,
    prof_id bigserial,
    zip_code character(4) NOT NULL,
    status_id bigserial NOT NULL,
    PRIMARY KEY (contact_id)
);

CREATE TABLE IF NOT EXISTS public.profession
(
    prof_id bigserial,
    profession character varying(50),
    PRIMARY KEY (prof_id),
    CONSTRAINT unique_profession_key UNIQUE (profession)
);

CREATE TABLE IF NOT EXISTS public.zip_code
(
    zip_code character(4),
    city character varying(50),
    province character varying(20),
    PRIMARY KEY (zip_code)
);

CREATE TABLE IF NOT EXISTS public.status
(
    status_id bigserial,
    status character varying(30),
    PRIMARY KEY (status_id)
);

CREATE TABLE IF NOT EXISTS public.interests
(
    interest_id bigserial,
    interests character varying(150),
    PRIMARY KEY (interest_id)
);

CREATE TABLE IF NOT EXISTS public.seeking
(
    seeking_id bigserial,
    seeking character varying(150),
    PRIMARY KEY (seeking_id)
);

CREATE TABLE IF NOT EXISTS public.contact_interest
(
    contact_id integer,
    interest_id integer,
    PRIMARY KEY (contact_id, interest_id)
);

CREATE TABLE IF NOT EXISTS public.contact_seeking
(
    contact_id integer,
    seeking_id integer,
    PRIMARY KEY (contact_id, seeking_id)
);

ALTER TABLE IF EXISTS public.my_contacts
    ADD FOREIGN KEY (prof_id)
    REFERENCES public.profession (prof_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.my_contacts
    ADD FOREIGN KEY (zip_code)
    REFERENCES public.zip_code (zip_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.my_contacts
    ADD FOREIGN KEY (status_id)
    REFERENCES public.status (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contact_interest
    ADD FOREIGN KEY (interest_id)
    REFERENCES public.interests (interest_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contact_interest
    ADD FOREIGN KEY (contact_id)
    REFERENCES public.my_contacts (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contact_seeking
    ADD FOREIGN KEY (seeking_id)
    REFERENCES public.seeking (seeking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contact_seeking
    ADD FOREIGN KEY (contact_id)
    REFERENCES public.my_contacts (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;



-- ============================================= INSERT STATEMENTS =============================================

INSERT INTO profession (profession)
VALUES 
('Medical Doctor'),
('Accountant'),
('Lawyer'),
('Architect'),
('Chef'),
('Teacher'),
('Software Developer'),
('Police Officer'),
('Journalist'),
('Waiting Staff'),
('Hairstylist'),
('Salesperson'),
('Engineer'),
('Secretary'),
('Delivery Person'),
('Firefighter');
SELECT * FROM profession


INSERT INTO zip_code (zip_code, city, province)
VALUES 
('6001', 'Port Elizabeth', 'Eastern Cape'),
('5201', 'East London', 'Eastern Cape'),
('9300', 'Bloemfontein', 'Free State'),
('9459', 'Welkom', 'Free State'),
('2000', 'Johannesburg', 'Gauteng'),
('0001', 'Pretoria', 'Gauteng'),
('4016', 'Durban', 'KwaZulu-Natal'),
('3201', 'Pietermaritzburg', 'KwaZulu-Natal'),
('0700', 'Polokwane', 'Limpopo'),
('0850', 'Tzaneen', 'Limpopo'),
('1200', 'Mbombela', 'Mpumalanga'),
('1034', 'eMalahleni', 'Mpumalanga'),
('8300', 'Kimberley', 'Northern Cape'),
('8800', 'Upington', 'Northern Cape'),
('2735', 'Mahikeng', 'North West'),
('2570', 'Klerksdorp', 'North West'),
('7102', 'Cape Town', 'Western Cape'),
('6531', 'George', 'Western Cape');
SELECT * FROM zip_code


INSERT INTO status (status)
VALUES 
('Online'),
('Offline'),
('Banned'),
('Deactivated');
SELECT * FROM status


INSERT INTO my_contacts (last_name, first_name, phone, email, gender, birthday, prof_id, zip_code, status_id)
VALUES
('Samuels', 'Mike', '0723451234', 'mike@email.com', 'M', '1991/01/23', 1, '6001', 1);
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
('');
SELECT * FROM my_contacts

INSERT INTO seeking (seeking)
VALUES 
('Marriage within the first year of dating with a stable individual'),
('Serious, long-term relationship that can lead to marriage but not actively seeking to marry any time soon'),
('Casual relationship, but open to committing to serious long-term relationship for the right person'),
('Open relationship'),
('Friendship/companionship. Open to long-distance or short-distance relations'),
('Strictly hookup');
SELECT * FROM seeking


INSERT INTO interests (interest) 
VALUES 
('Reading e.g. novels, magazines,  journals'), 
('Writing e.g. blogging, journaling'),
('Field sports e.g. soccer, netball, hockey, athletics'), 
('Water sports e.g. waterpolo, swimming '),
('Extreme sports e.g. skydiving'),
('Boardgames e.g. chess, 30seconds'), 
('Watching movies/series'),
('Computer/video games'),
('Crotchet/knitting'), 
('Singing'), 
('Dancing'),
('Drawing'),
('Jogging/running'),
('Taking walks'),
('Stargazing/astrology');
SELECT * FROM interests


INSERT INTO contact_seeking 
VALUES 
(1, 1);


INSERT INTO contact_interest 
VALUES 
(1, 13),
(1, 1),
(1, 10),
(1, 15),
(1, 2)



-- ============================== QUERIES ==============================

-- ============================== CONTACT INFO ==============================

SELECT status.status,
contact.first_name,
contact.last_name,
contact.gender,
contact.birthday,
prof.profession,
zip.city,
zip.province,
s.seeking
FROM my_contacts AS contact
JOIN profession AS prof
ON contact.prof_id = prof.prof_id
JOIN zip_code AS zip
ON contact.zip_code = zip.zip_code
JOIN status 
ON contact.status_id = status.status_id
JOIN contact_seeking AS c_s
ON contact.contact_id = c_s.contact_id
JOIN seeking AS s
ON c_s.seeking_id = s.seeking_id





-- ============================== SEARCH BY INTERESTS ==============================

SELECT 
contact.first_name,
contact.last_name,
zip.city,
zip.province,
i.interest,
contact.phone
FROM my_contacts AS contact
JOIN 
contact_interest AS c_i
ON contact.contact_id = c_i.contact_id
JOIN interests AS i
ON c_i.interest_id = i.interest_id
JOIN zip_code AS zip
ON contact.zip_code = zip.zip_code
WHERE i.interest_id = 15


-- ============================== SEARCH BY SEEKING ==============================

SELECT 
contact.first_name,
contact.last_name,
zip.city,
zip.province,
s.seeking,
contact.phone
FROM my_contacts AS contact
JOIN contact_seeking AS c_s
ON contact.contact_id = c_s.contact_id
JOIN seeking AS s
ON c_s.seeking_id = s.seeking_id
JOIN zip_code AS zip
ON contact.zip_code = zip.zip_code
WHERE s.seeking_id = 1








